apiVersion: v1
kind: Namespace
metadata:
  name: srv
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Service
metadata:
  namespace: srv
  labels:
    app: servicetest
  name: servicetest
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: servicetest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicetest1
  namespace: srv
  labels:
    app: servicetest

spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicetest
      ver: "1"
  template:
    metadata:
      labels:
        app: servicetest
        ver: "1"
    spec:
      containers:
        - name: servicetest
          image: sz3jdii/service_test:latest
          ports:
            - containerPort: 8080
          env:
            - name: TEST_STRING
              value: service_test_A
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicetest2
  namespace: srv
  labels:
    app: servicetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicetest
      ver: "2"
  template:
    metadata:
      labels:
        app: servicetest
        ver: "2"
    spec:
      containers:
        - name: servicetest
          image: sz3jdii/service_test:latest
          ports:
            - containerPort: 8080
          env:
            - name: TEST_STRING
              value: service_test_B
          imagePullPolicy: Always