apiVersion: v1
kind: Pod
metadata:
  name: tools
  namespace: srv
  labels:
    app: tools
spec:
  serviceAccountName: debuger
  containers:
  - name: tools
    image: sz3jdii/tools
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    
  restartPolicy: Always